### ISSUE TITLE
Google phishlet

### ISSUE THREAD

**Issue by EvilGreys** [ProjectTakayama/EVILGINX3-PHISHLET#1]
Hi Takayama. I bought google,coinbase,blockchain phishlet from you. I made some changes to Blockchain and was able to add automatic coin withdrawal scripts. Would love to work with you, your phishlets work great !!!
thanks for your work.

**Comment by ProjectTakayama** [comment]
Thank you

**Comment by TarasaSec** [comment]
I'm also interested in trying this

> Hi Takayama. I bought google,coinbase,blockchain phishlet from you. I made some changes to Blockchain and was able to add automatic coin withdrawal scripts. Would love to work with you, your phishlets work great !!! thanks for your work.
